package:
  name: pooch
  version: 1.8.2
  top-level:
    - pooch
source:
  url: https://files.pythonhosted.org/packages/a8/87/77cc11c7a9ea9fd05503def69e3d18605852cd0d4b0d3b8f15bbeb3ef1d1/pooch-1.8.2-py3-none-any.whl
  sha256: 3529a57096f7198778a5ceefd5ac3ef0e4d06a6ddaf9fc2d609b806f25302c47
requirements:
  run:
    - platformdirs
    - requests
    - packaging
about:
  home: https://www.fatiando.org/pooch
  PyPI: https://pypi.org/project/pooch
  summary: A friend to fetch your data files
  license: BSD-3-Clause
extra:
  recipe-maintainers:
    - PUT_YOUR_GITHUB_USERNAME_HERE
