package:
  name: pybamm
  version: 24.9.0
  top-level:
    - pybamm
source:
  # broken sdist because of missing FindSuiteSparse.cmake and FindSUNDIALS.cmake files
  url: https://github.com/pybamm-team/PyBaMM/archive/refs/tags/v24.9.0.tar.gz
  sha256: 20f9d8d62dba2d847346d62bca519a369d862ac9f6262cc57a9222fde0c04858
  patches:
    - patches/0001-Set-PYBIND11_FINDPYTHON-ON-for-FindPython.patch
    - patches/0002-Handle-CMake-arguments-for-Emscripten.patch
    - patches/0003-Find-CasADi-and-OpenBLAS.patch
    - patches/0004-Add-more-args-to-the-CMake-invocation.patch
build:
  ldflags: -L${WASM_LIBRARY_DIR}/lib
  script: |
      # We'll likely have way more stuff to do here, let's see...
      git clone https://github.com/pybind/pybind11.git --depth 1 pybind11
requirements:
  host:
    - openblas
    - suitesparse
    - sundials
    - casadi
  run:
    - numpy
    - scipy
    - casadi
    - xarray
    - anytree
    - sympy
    - typing-extensions
    - pandas
    - pooch
about:
  home: https://pybamm.org/
  PyPI: https://pypi.org/project/pybamm
  summary: Python Battery Mathematical Modelling
  license: BSD-3-Clause
