package:
  # We need to use a non-Python CasADi (i.e. the C++ library) to build PyBaMM
  # against, because libraries from the CasADi Python wheel are ELF binaries
  # and they won't work when cross-compiling to WASM.
  name: casadi
  version: 3.6.7
source:
  url: https://github.com/casadi/casadi/archive/refs/tags/3.6.7.tar.gz
  sha256: 47602bab2aa187bfa8280cc4fa7d68ee19abbbdfeb90991e9eb3dd88465fd18b
requirements:
  run:
    - numpy
  executable:
    - swig
build:
  type: shared_library
  exports: requested
  cflags: |
    -fexceptions -frtti
  cxxflags: |
    -fexceptions -frtti
  ldflags: |
    -fexceptions
  script: |
    mkdir -p build
    cd build

    export LDFLAGS="${SIDE_MODULE_LDFLAGS} -L${WASM_LIBRARY_DIR}/lib"

    emcmake cmake \
      -DCMAKE_BUILD_TYPE=Release \
      -DCMAKE_INSTALL_PREFIX=${WASM_LIBRARY_DIR} \
      -DWITH_PYTHON=OFF \
      -DWITH_DOC=OFF \
      -DWITH_EXAMPLES=OFF \
      -DWITH_TESTS=OFF \
      -DWITH_BONMIN=OFF \
      -DWITH_IPOPT=OFF \
      -DWITH_OSQP=OFF \
      -DWITH_QPOASES=OFF \
      -DWITH_QUIPLES=OFF \
      -DWITH_GLPK=OFF \
      -DWITH_HSL=OFF \
      -DWITH_MA27=OFF \
      -DWITH_MA57=OFF \
      -DWITH_MA77=OFF \
      -DWITH_MA86=OFF \
      -DWITH_MA97=OFF \
      -DWITH_MUMPS=OFF \
      -DWITH_PARDISO=OFF \
      -DWITH_SUPERLU=OFF \
      -DWITH_SUPERLU_MT=OFF \
      -DWITH_WSMP=OFF \
      -DWITH_UMFPACK=OFF \
      -DWITH_AMD=OFF \
      -DWITH_COLAMD=OFF \
      -DWITH_CAMD=OFF \
      -DWITH_CXSPARSE=OFF \
      -DWITH_KLU=OFF \
      -DWITH_CASADI_MEX=OFF \
      -DWITH_CASADI_OCTAVE=OFF \
      -DWITH_CASADI_PYTHON=OFF \
      -DWITH_CASADI_MATLAB=OFF \
      -DWITH_CASADI_SCILAB=OFF \
      -DWITH_CASADI_R=OFF \
      -DWITH_CASADI_PYTHON3=OFF \
      -DWITH_CASADI_MATLAB3=OFF \
      -DWITH_CASADI_SCILAB3=OFF \
      -DWITH_CASADI_R3=OFF \
      -DWITH_CASADI_PYTHON2=OFF \
      -DWITH_CASADI_MATLAB2=OFF \
      -DWITH_CASADI_SCILAB2=OFF \
      -DWITH_CASADI_R2=OFF \
      -DWITH_CASADI_PYTHON2=OFF \
      -DCMAKE_SHARED_LINKER_FLAGS="${LDFLAGS}" \
      -DCMAKE_C_FLAGS="${SIDE_MODULE_CFLAGS}"
      ..

about:
  home: http://casadi.org
  PyPI: https://pypi.org/project/casadi
  summary: CasADi -- framework for algorithmic differentiation and numeric optimization
  license: LGPL-3.0+
