name: Build WASM dependencies and PyBaMM

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y cmake build-essential libssl-dev pkg-config

      - name: Check out Pyodide
        uses: actions/checkout@v4
        with:
          repository: pyodide/pyodide
          path: pyodide_checkout
          submodules: recursive

      - name: Overwrite previous recipes and copy new ones
        run: cp -r recipes/* pyodide_checkout/packages/

      - name: Build Pyodide distribution
        working-directory: pyodide_checkout/
        run: |
          PYODIDE_CORES=$(nproc)
          PYODIDE_JOBS="${PYODIDE_CORES}" PYODIDE_PACKAGES="pybamm" make

      - name: Upload Pyodide distribution
        uses: actions/upload-artifact@v4
        with:
          name: pyodide_dist
          path: pyodide_checkout/dist/*
          if-no-files-found: error
